# http://travis-ci.org/#!/meisam/YSmart
language: python
python:
    - 2.7
env:
    - CORRELATION=true
install:
    - pip install antlr_python_runtime
    - python setup.py install
script:
    - python -m ysmart.test.testysmartjobgenerator
    - python -m ysmart.test.testysmartospark
    - python -m ysmart.test.testysmartparser