# http://travis-ci.org/#!/meisam/YSmart
language: python
python:
    - 2.7
    - pypy
    - 3.2
    - 3.3
env:
    - CORRELATION=true
    - CORRELATION=false
install:
    - pip install antlr_python_runtime
    - python setup.py install
script:
    - python -m ysmart.test.testysmartjobgenerator
    - python -m ysmart.test.testysmartospark
    - python -m ysmart.test.testysmartparser
